{{- if .Values.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "milvus-tenant.storageClassName" . }}
  labels:
    {{- include "milvus-tenant.labels" . | nindent 4 }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: {{ .Values.storageClass.provisioner }}
parameters:
  type: {{ .Values.storageClass.parameters.type }}
  iops: {{ .Values.storageClass.parameters.iops | quote }}
  throughput: {{ .Values.storageClass.parameters.throughput | quote }}
  fsType: {{ .Values.storageClass.parameters.fsType }}
  encrypted: {{ .Values.storageClass.parameters.encrypted | quote }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
{{- end }}
