apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: milvus-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  
  source:
    repoURL: https://github.com/zilliztech/milvus-operator/releases/download/v1.1.2/milvus-operator-1.1.2.tgz
    helm:
      releaseName: milvus-operator
      values: |
        nodeSelector:
          karpenter.sh/nodepool: general-pool

  destination:
    server: https://kubernetes.default.svc
    namespace: milvus-operator

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true