apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: milvus-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default  
  source:
    repoURL: https://zilliztech.github.io/milvus-operator
    chart: milvus-operator
    targetRevision: "1.1.2"
    helm:
      releaseName: milvus-operator
      values: |
        nodeSelector:
          role: general
  destination:
    server: https://kubernetes.default.svc
    namespace: milvus-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: batch
      kind: Job
      name: milvus-operator-checker
      jsonPointers:
        - /spec