apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cortex-ingestion
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/opengig/cortex.git
    targetRevision: kshitij/s3anddb
    path: prod/cortex-ingestion/helm/cortex-ingestion-chart
    helm:
      releaseName: cortex-ingestion
  destination:
    server: https://kubernetes.default.svc
    namespace: cortex-ingestion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      jqPathExpressions:
        - .metadata.annotations
        - .spec.rules
        - .spec.tls