apiVersion: v1
kind: Service
metadata:
  name: nextjs
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: nextjs
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nextjs
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP