apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextjs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/opengig/cortex.git
    targetRevision: HEAD
    path: prod/nextjs/helm/nextjs-chart
    helm:
      releaseName: nextjs
  destination:
    server: https://kubernetes.default.svc
    namespace: nextjs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      jqPathExpressions:
        - .metadata.annotations
        - .spec.rules
        - .spec.tls