{{- if .Values.certificate.create }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.org_id }}-milvus-wildcard-cert
  namespace: {{ include "milvus-tenant.namespace" . }}
  labels:
    {{- include "milvus-tenant.labels" . | nindent 4 }}
spec:
  secretName: {{ include "milvus-tenant.tlsSecretName" . }}
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name }}
    kind: {{ .Values.certificate.issuerRef.kind }}
  commonName: "*.{{ .Values.ingress.domain }}"
  dnsNames:
    - "*.{{ .Values.ingress.domain }}"
    - "{{ .Values.ingress.domain }}"
  duration: {{ .Values.certificate.duration }}
  renewBefore: {{ .Values.certificate.renewBefore }}
{{- end }}
