{{- if .Values.ingress.grpc.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.org_id }}-milvus-grpc-ingress
  namespace: {{ include "milvus-tenant.namespace" . }}
  labels:
    {{- include "milvus-tenant.labels" . | nindent 4 }}
  annotations:
    nginx.org/http2: "true"
    nginx.org/grpc-services: {{ include "milvus-tenant.serviceName" . | quote }}
    nginx.org/proxy-connect-timeout: {{ .Values.ingress.grpc.proxyConnectTimeout | quote }}
    nginx.org/proxy-read-timeout: {{ .Values.ingress.grpc.proxyReadTimeout | quote }}
    nginx.org/proxy-send-timeout: {{ .Values.ingress.grpc.proxySendTimeout | quote }}
    {{- with .Values.ingress.grpc.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ include "milvus-tenant.grpcHost" . }}
      secretName: {{ .Values.ingress.tlsSecretName | default (include "milvus-tenant.tlsSecretName" .) }}
  rules:
    - host: {{ include "milvus-tenant.grpcHost" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "milvus-tenant.serviceName" . }}
                port:
                  number: 19530
{{- end }}
