{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.org_id }}-milvus-monitor
  namespace: {{ include "milvus-tenant.namespace" . }}
  labels:
    {{- include "milvus-tenant.labels" . | nindent 4 }}
    release: {{ .Values.monitoring.releaseLabel }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.org_id }}
      app.kubernetes.io/name: milvus
      milvus.io/service: "true"
  namespaceSelector:
    matchNames:
      - {{ include "milvus-tenant.namespace" . }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.monitoring.interval }}
      relabelings:
        - action: replace
          replacement: {{ .Values.org_id }}
          targetLabel: org_id
        - action: replace
          replacement: {{ .Values.org_id }}
          targetLabel: organization
{{- end }}
