apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-ingestion-config
  namespace: cortex-ingestion
  labels:
    app.kubernetes.io/name: cortex-ingestion
    app.kubernetes.io/component: config
data:
  ENV: "prod"
  LOG_LEVEL: "INFO"
  AWS_REGION: "us-east-1"
  ORG: "cortexai"

  FALKORDB_HOST: "a01124789164647a89957dfc083d468d-d04bceb9723de769.elb.us-east-1.amazonaws.com"
  FALKORDB_PORT: "6379"
  DB_CONNECTIONS: "80"
  FALKOR_ORG_SPECIFIC_CLUSTER: "true"

  KAFKA_BOOTSTRAP_SERVERS: "boot-qlghp0x1.c1.kafka-serverless.us-east-1.amazonaws.com:9098"
  KAFKA_TOPIC: "document-ingestion"
  KAFKA_GROUP_ID: "ingestion-service-group"
  KAFKA_SECURITY_PROTOCOL: "SASL_SSL"
  KAFKA_SASL_MECHANISM: "AWS_MSK_IAM"
  KAFKA_AUTO_OFFSET_RESET: "earliest"

  STORAGE_BACKEND: "s3"
  MINIO_ENDPOINT: "localhost:9000"
  MINIO_SECURE: "false"
  MINIO_BUCKET: "documents"

  ENABLE_VESPA: "true"
  VESPA_CONFIGSERVER_URL: "https://configserver.usecortex.ai"
  VESPA_TENANT: "cortex"
  VESPA_APP_NAME: "cortex-ingestion"

  ENABLE_MILVUS: "true"
  MILVUS_URI: "https://cortex-common.milvusdb.usecortex.ai:443"
  MILVUS_DEFAULT_PARTITIONS: "64"

  VECTOR_PUSH_URL: "https://vector.usecortex.ai/"

  CORTEX_API_KEYS_TABLE_NAME: "cortex_user_api_keys_prod"
