apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falkordb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/opengig/cortex.git
    targetRevision: HEAD
    path: prod/falkordb/helm/falkor-chart
    helm:
      releaseName: falkordb
  destination:
    server: https://kubernetes.default.svc
    namespace: falkordb-cortex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps.kubeblocks.io
      kind: Cluster
      jsonPointers:
        - /spec/componentSpecs/0/serviceVersion
        - /spec/componentSpecs/0/disableExporter
