apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-inc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://helm.nginx.com/stable
    chart: nginx-ingress
    targetRevision: "1.4.0"
    helm:
      releaseName: nginx-inc
      values: |
        controller:
          ingressClass:
            name: nginx-inc
            setAsDefaultIngress: true
          
          # gRPC support (Milvus)
          config:
            entries:
              http2: "true"
          
          # TLS passthrough for TCP/SNI routing (FalkorDB)
          enableTLSPassthrough: true
          
          globalConfiguration:
            create: true
            spec:
              listeners:
                - name: tls-passthrough
                  port: 6380
                  protocol: TLS_PASSTHROUGH
          
          # AWS NLB
          service:
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
              service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
          
          replicaCount: 2
          
          nodeSelector:
            karpenter.sh/nodepool: general-pool

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-inc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true