apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: cortex-ingestion
  {{- if .Values.serviceAccount.irsaRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.irsaRoleArn }}
  {{- end }}