apiVersion: v1
kind: Service
metadata:
  name: cortex-ingestion
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: cortex-ingestion
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cortex-ingestion
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP