apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-app-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: cortex-app
    app.kubernetes.io/component: config
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}