apiVersion: v1
kind: Service
metadata:
  name: cortex-app
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: cortex-app
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cortex-app
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP