{{- $fullName := printf "%s-%s-%s" .Values.clusterName .Values.organization .Values.tenantId}}
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
spec:
  terminationPolicy: Delete
  clusterDef: falkordb
  topology: replication

  componentSpecs:
  # --- DATA NODES ---
  - name: falkordb
    serviceVersion: "4.12.5"
    replicas: {{ .Values.dataNode.replicas }}
    {{- if .Values.auth.useSharedSecret }}
    # Override default account password with shared secret
    systemAccounts:
    - name: default
      secretRef:
        name: {{ .Values.auth.sharedSecretName }}
        namespace: {{ .Values.auth.sharedSecretNamespace }}
        password: {{ .Values.auth.sharedSecretKey }}
    {{- end }}
    disableExporter: false
    resources:
      requests:
        cpu: {{ .Values.dataNode.resources.requests.cpu | quote }}
        memory: {{ .Values.dataNode.resources.requests.memory | quote }}
      limits:
        cpu: {{ .Values.dataNode.resources.limits.cpu | quote }}
        memory: {{ .Values.dataNode.resources.limits.memory | quote }}
    
    schedulingPolicy:
      nodeSelector:
        {{- toYaml .Values.dataNode.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.dataNode.tolerations | nindent 8 }}
      
    volumeClaimTemplates:
    - name: data
      spec:
        storageClassName: {{ .Values.dataNode.storage.storageClassName }}
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.dataNode.storage.size }}

  # --- SENTINEL NODES ---
  - name: falkordb-sent
    replicas: {{ .Values.sentinelNode.replicas }}
    resources:
      requests:
        cpu: {{ .Values.sentinelNode.resources.requests.cpu | quote }}
        memory: {{ .Values.sentinelNode.resources.requests.memory | quote }}
      limits:
        cpu: {{ .Values.sentinelNode.resources.limits.cpu | quote }}
        memory: {{ .Values.sentinelNode.resources.limits.memory | quote }}
    
    schedulingPolicy:
      nodeSelector:
        {{- toYaml .Values.sentinelNode.nodeSelector | nindent 8 }}
      
    volumeClaimTemplates:
    - name: data
      spec:
        storageClassName: {{ .Values.sentinelNode.storage.storageClassName }}
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.sentinelNode.storage.size }}