{{- if .Values.ingress.enabled }}
{{- if not .Values.ingress.useWildcardCert }}
{{- /* LEGACY: Only create Ingress when NOT using wildcard cert + TransportServer */}}
{{- $fullName := printf "%s-%s-%s" .Values.clusterName .Values.organization .Values.tenantId }}
{{- $hostname := printf "%s-%s.%s" .Values.organization .Values.tenantId .Values.ingress.domain }}
{{- $certSecretName := printf "%s-tls-cert" $fullName }}
{{- $stunnelService := printf "%s-stunnel" $fullName }}
---
# Ingress for FalkorDB with SSL Passthrough (LEGACY - not used with TransportServer)
# 
# IMPORTANT: This requires NGINX Ingress Controller with SSL passthrough enabled:
#   kubectl patch deployment ingress-nginx-controller -n ingress-nginx \
#     --type='json' \
#     -p='[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value": "--enable-ssl-passthrough"}]'
#
# Connection URL: rediss://{{ $hostname }}:443
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "TCP"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - hosts:
    - {{ $hostname }}
    secretName: {{ $certSecretName }}
  rules:
  - host: {{ $hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $stunnelService }}
            port:
              number: 6380
{{- end }}
{{- end }}
