{{- if .Values.ingress.enabled }}
{{- if not .Values.ingress.useWildcardCert }}
{{- $fullName := printf "%s-%s-%s" .Values.clusterName .Values.organization .Values.tenantId }}
{{- $hostname := printf "%s-%s.%s" .Values.organization .Values.tenantId .Values.ingress.domain }}
{{- $certSecretName := printf "%s-tls-cert" $fullName }}
---
# TLS Certificate for FalkorDB ingress (per-tenant)
# Only created when useWildcardCert is false
# Requires cert-manager to be installed in the cluster
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-certificate
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ $certSecretName }}
  issuerRef:
    name: {{ .Values.ingress.tls.issuerName }}
    kind: {{ .Values.ingress.tls.issuerKind }}
  commonName: {{ $hostname }}
  dnsNames:
  - {{ $hostname }}
  duration: 2160h    # 90 days
  renewBefore: 360h  # 15 days before expiry
{{- end }}
{{- end }}
